Fix schema return type
mypy checks fail because the schema return type is lru_cache:

```
singer_sdk/streams/sql.py:82: error: Signature of "schema" incompatible with supertype "Stream"  [override]
singer_sdk/streams/sql.py:154: error: Argument "schema" to "get_selected_schema" has incompatible type "_lru_cache_wrapper[Dict[Any, Any]]"; expected "Dict[Any, Any]"  [arg-type]
Found 2 errors in 1 file (checked 59 source files)
```

The update should pass over the `_lru_cache_wrapper` type and return a `Dict` as expected