fix: `AttributeError: object has no attribute '_requests_session'` when accessing public property during stream initialisation (#2965)
* Initialise `_requests_session` on the class to prevent `AttributeError` when accessing public property during stream initialisation

* Unnecessary to instantiate `_requests_session` at the end of stream initialisation, as accessing the public property will already do this if required

* Remove private `_http_headers` attribute and initialize current class attributes before parent class

* Remove class attribute

---------

Co-authored-by: Edgar Ramírez Mondragón <edgarrm358@gmail.com>